version: '3.4'

services:
    productDb:
        image: mongo

    productDbExpress:
        image: mongo-express

    ecom.product.api:
        image: ${DOCKER_REGISTRY-}ecomproductapi
        build:
            context: .
            dockerfile: src/Product/ECom.Product.Api/Dockerfile
    cartDb:
        image: redis

    ecom.cart.api:
      image: ${DOCKER_REGISTRY-}ecomcartapi
      build:
        context: .
        dockerfile: src/Cart/ECom.Cart.Api/Dockerfile

